//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_for_App_Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordHistory
    {
        public int PasswordHistoryId { get; set; }
        public string OldPassword { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
